CREATE TABLE IF NOT EXISTS USERS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    VERSION INTEGER,
    USER_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(100),
    ROLE_ID INTEGER,
    IS_ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS ROLE(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20)
);